# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bS0UyT5Lt1WpEbf42OLYchwIVjfYdcTR
"""

import json
import statistics

# Öğrencilerin bilgilerini tutacak array (liste)
ogrenciler = []

# Öğrenci ekleme fonksiyonu
def ogrenci_ekle():
    print("Yeni Öğrenci Ekleme")
    ad = input("Öğrencinin adı: ")
    soyad = input("Öğrencinin soyadı: ")
    numara = input("Öğrencinin numarası (3 haneli): ")

    # Öğrenci numarasının 3 haneli olmasına dikkat et
    if len(numara) != 3 or not numara.isdigit():
        print("Geçersiz numara! Numara 3 haneli bir sayı olmalıdır.")
        return

    # Öğrenci notlarını al
    try:
        ders_notlari = []
        for i in range(3):  # 3 ders notu girecek
            not_ = float(input(f"Ders {i+1} notu (0-100 arası): "))
            if not (0 <= not_ <= 100):
                print("Notlar 0 ile 100 arasında olmalıdır!")
                return
            ders_notlari.append(not_)
    except ValueError:
        print("Geçersiz not girişi!")
        return

    # Aynı numarayla öğrenci eklenip eklenmediğini kontrol et
    for ogrenci in ogrenciler:
        if ogrenci["numara"] == numara:
            print("Bu numara ile bir öğrenci zaten mevcut!")
            return

    # Öğrenci bilgisini listeye ekle
    ogrenci = {
        "ad": ad,
        "soyad": soyad,
        "numara": numara,
        "notlar": ders_notlari
    }
    ogrenciler.append(ogrenci)
    print("Öğrenci başarıyla eklendi!")

# Öğrenci bilgilerini listeleme fonksiyonu
def ogrenci_listele():
    if not ogrenciler:
        print("Henüz öğrenci eklenmedi!")
        return
    print("\nÖğrenci Listesi:")
    print(f"{'Numara':<10} {'Adı Soyadı':<20} {'Notlar'}")
    for ogrenci in ogrenciler:
        notlar = ', '.join(map(str, ogrenci["notlar"]))
        print(f"{ogrenci['numara']:<10} {ogrenci['ad']} {ogrenci['soyad']:<20} {notlar}")

# Not analizi fonksiyonu
def not_analizi():
    if not ogrenciler:
        print("Henüz öğrenci eklenmedi!")
        return
    notlar = [not_ for ogrenci in ogrenciler for not_ in ogrenci["notlar"]]
    if not notlar:
        print("Öğrenci notları bulunamadı!")
        return
    # En yüksek not, en düşük not ve sınıf ortalamasını hesapla
    en_yuksek = max(notlar)
    en_dusuk = min(notlar)
    ortalama = statistics.mean(notlar)

    print(f"En yüksek not: {en_yuksek}")
    print(f"En düşük not: {en_dusuk}")
    print(f"Sınıf ortalaması: {ortalama:.2f}")

# Menü gösterme ve kullanıcıdan seçim alma
def menu():
    while True:
        print("\nÖğrenci Bilgi Sistemi")
        print("1. Öğrenci Ekleme")
        print("2. Öğrenci Bilgilerini Listeleme")
        print("3. Not Analizi")
        print("4. Çıkış")

        secim = input("Bir seçenek girin (1-4): ")

        if secim == '1':
            ogrenci_ekle()
        elif secim == '2':
            ogrenci_listele()
        elif secim == '3':
            not_analizi()
        elif secim == '4':
            print("Çıkılıyor...")
            break
        else:
            print("Geçersiz seçim! Lütfen 1-4 arasında bir seçim yapın.")

# Programı başlat
menu()

